services:  
  postgres:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    hostname: demo-postgres
    container_name: demo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/ 
    ports:
      - '5433:5432'
    volumes:
      - ./db:/var/lib/postgresql/data/:rw
      - ./sql-scripts:/sql-scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    networks:
      - test-network

networks:
  test-network:
    name: test-network
    external: true